name: ajphoto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.71679
title: AJPhoto Grid Site Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0023c'
    - '#010101'
    - '#ffffff'
    - '#575757'
    - '#00ffff'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
