name: ajphoto
favicon: null
layout_spectrum: 0.21954690432175994
typography_spectrum: 0.15276334062218666
title: AJPhoto Grid Site Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0023c'
    - '#010101'
    - '#ffffff'
    - '#575757'
    - '#00ffff'
  brandStrength: 0.6875
  lightness: 0.2768004483077675
  saturation: 0.19354514661245048
  rhythmicContrast: 0.9121492814738303
purpose: []
