name: ajphoto
favicon: null
layout_spectrum: 0.68324
typography_spectrum: 0.90102
title: AJPhoto Grid Site Test
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#e6e6e6'
    - '#454545'
    - '#bababa'
    - '#888888'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
