title: AJPhoto Grid Site Test
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3375149
  lightness: 1
  brandStrength: 1
  brandColors:
    - '#a0023c'
    - '#010101'
    - '#ffffff'
    - '#575757'
    - '#00ffff'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: ajphoto
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.71679
layout_spectrum: 1
